import streamlit as st
import pandas as pd

st.set_page_config(page_title="Fraud BI Dashboard", page_icon="🛡️")
st.title("🛡️ Real-Time Fraud Detection BI Dashboard")

# Load the ETL results generated by pipeline/etl_pipeline.py
try:
    df = pd.read_csv('data/processed_transactions.csv')
    
    # Metrics
    c1, c2 = st.columns(2)
    c1.metric("Total Analyzed", len(df))
    c2.metric("Fraud Cases (Class 1)", len(df[df['Class'] == 1]))

    st.write("### 📊 Risk Distribution")
    st.bar_chart(df['Risk_Category'].value_counts())

    st.write("### 📋 Latest Flagged Transactions")
    st.dataframe(df[['Time', 'Amount', 'Risk_Category', 'Class', 'pipeline_run_at']])
except FileNotFoundError:
    st.error("Processed data not found. Please run 'python pipeline/etl_pipeline.py' first!")
